# Generated by Django 3.2.3 on 2021-06-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twiter', '0002_auto_20210626_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='favorite',
        ),
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
