# Generated by Django 3.2.3 on 2021-06-28 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('twiter', '0003_auto_20210628_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='favorite_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
