# Generated by Django 3.2.3 on 2021-06-30 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twiter', '0004_favorite_favorite_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
