# Generated by Django 3.2.3 on 2021-08-05 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twiter', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
